/* =====================================================================
   PEDIATRICS — Modernized database (SQL Server 2022 / level 160)
   Requirements source: Requirements Document V6.1 (Manuel Razo)
   Compliance: NOM-004-SSA3-2012 (Mexican clinical record standard)
   Generated: 2026-09-08

   DESIGN DECISIONS (summary — see chat response for details):
   - GUID (UNIQUEIDENTIFIER) on the root entities exposed via API:
     users, patients, appointments, consultations, prescriptions.
     The GUID is generated by the application layer (not the DB): that's
     why these columns have NO DEFAULT. This lets the domain know the
     entity's Id before calling SaveChanges() (needed for aggregates/
     domain events), and keeps PK generation independent of the engine.
     If clustered index fragmentation needs mitigating (a real issue
     with UNIQUEIDENTIFIER as a PK in SQL Server), that's solved by
     generating a "sequential"/COMB GUID in C# — not by delegating to
     NEWSEQUENTIALID().
   - Satellite/detail tables (history, vaccinations, prescription
     medications, review of systems, etc.) use INT IDENTITY: they are
     never exposed or referenced independently, always accessed through
     the parent's GUID.
   - audit_log uses BIGINT IDENTITY: it's a high-volume, insert-only
     table; a GUID there adds no value and would penalize inserts.
   - record_number (patient) and prescription_number (prescription) are
     auto-incrementing integers independent of the GUID: the GUID is the
     technical/API identifier; the number is the legal/human identifier
     already required by the requirements (REQ-PAC-003, REQ-REC-002).
   - Logical deletion (active BIT) on patient/consultation/prescription
     instead of a physical DELETE, to comply with the 5-year retention
     requirement (REQ-PAC-018, REQ-EXT-001) and REQ-REC-005 (cancel,
     don't delete).
   ===================================================================== */

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE DATABASE [PediatricsV2];
GO
ALTER DATABASE [PediatricsV2] SET READ_COMMITTED_SNAPSHOT ON;
GO
USE [PediatricsV2];
GO

/* =====================================================================
   1. USERS  (REQ-USR-001 to 016 / REQ-SEC-001 to 005)
   ===================================================================== */

CREATE TABLE dbo.roles (
    id      INT IDENTITY(1,1) PRIMARY KEY,
    name    NVARCHAR(30) NOT NULL UNIQUE
        CHECK (name IN (N'Administrador', N'Medico', N'Recepcionista'))
);
GO
INSERT INTO dbo.roles (name) VALUES (N'Administrador'), (N'Medico'), (N'Recepcionista');
GO

-- Base authentication table. GUID: it's the natural JWT "sub" and avoids
-- user enumeration on admin endpoints (REQ-USR-006/007).
CREATE TABLE dbo.users (
    id                  UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    username            NVARCHAR(50)  NOT NULL UNIQUE,
    email               NVARCHAR(100) NOT NULL UNIQUE,           -- REQ-USR-003: recovery by email
    password_hash       NVARCHAR(256) NOT NULL,                  -- REQ-SEC-004: never plain text
    active              BIT NOT NULL DEFAULT 1,
    created_at          DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
    last_login_at       DATETIME2(0) NULL,
    deactivated_at      DATETIME2(0) NULL                        -- REQ-USR-015: logical deletion, not physical
);
GO
CREATE INDEX IX_active_users ON dbo.users(id) WHERE active = 1;
GO

CREATE TABLE dbo.users_role(
    user_id           UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.users(id),
    role_id           INT NOT NULL REFERENCES dbo.roles(id),   -- REQ-USR-005
    CONSTRAINT PK_OrderItems PRIMARY KEY (user_id, role_id)
);
GO

-- Extended physician profile (1:1 with users, shared PK).
CREATE TABLE dbo.physicians (
    user_id                       UNIQUEIDENTIFIER NOT NULL PRIMARY KEY
        REFERENCES dbo.users(id) ON DELETE CASCADE,
    full_name                     NVARCHAR(100) NOT NULL,
    birth_date                    DATE NOT NULL,
    gender                        NVARCHAR(10) NOT NULL CHECK (gender IN (N'Masculino', N'Femenino', N'Otro')),
    professional_license_number   NVARCHAR(20) NOT NULL UNIQUE,        -- REQ-USR-010
    educational_institution       NVARCHAR(100) NOT NULL,
    specialty                     NVARCHAR(100) NOT NULL,
    signature                     VARBINARY(MAX) NULL                  -- REQ-USR-009 / REQ-REC-002 (signature on prescription)
);
GO

-- Extended receptionist profile (1:1 with users).
CREATE TABLE dbo.receptionists (
    user_id           UNIQUEIDENTIFIER NOT NULL PRIMARY KEY
        REFERENCES dbo.users(id) ON DELETE CASCADE,
    full_name         NVARCHAR(100) NOT NULL,
    birth_date        DATE NOT NULL,
    gender            NVARCHAR(10) NOT NULL CHECK (gender IN (N'Masculino', N'Femenino', N'Otro'))
);
GO

-- Clinic/office info, editable by the admin without touching code (REQ-SOP-003)
-- and used to print the prescription (REQ-REC-002).
CREATE TABLE dbo.clinic (
    id        INT NOT NULL PRIMARY KEY CHECK (id = 1),   -- single row (singleton pattern)
    name      NVARCHAR(100) NOT NULL,
    address   NVARCHAR(150) NOT NULL,
    phone     NVARCHAR(15)  NOT NULL
);
GO

CREATE TABLE dbo.refresh_tokens (
    id                 UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    user_id            UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.users(id) ON DELETE CASCADE,
    token_hash         NVARCHAR(256) NOT NULL,
    created_at         DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
    expires_at         DATETIME2(0) NOT NULL,
    revoked            BIT NOT NULL DEFAULT 0,
    created_by_ip      NVARCHAR(45) NULL
);
GO
CREATE INDEX IX_refresh_tokens_user ON dbo.refresh_tokens(user_id) WHERE revoked = 0;
GO

-- Password recovery: temporary password generated by the admin,
-- expires in 24h, forces a change on next login.
CREATE TABLE dbo.password_resets (
    id                    UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    user_id               UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.users(id) ON DELETE CASCADE,
    admin_id              UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.users(id),
    temp_password_hash    NVARCHAR(256) NOT NULL,
    created_at            DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
    expires_at            DATETIME2(0) NOT NULL,       -- created_at + 24h, computed in the application
    used                  BIT NOT NULL DEFAULT 0
);
GO

-- Unified audit log (REQ-USR-016, REQ-PAC-020, REQ-SOP-005).
-- BIGINT IDENTITY: high-volume append-only table, a GUID adds no value here.
CREATE TABLE dbo.audit_log (
    id            BIGINT IDENTITY(1,1) PRIMARY KEY,
    user_id       UNIQUEIDENTIFIER NULL REFERENCES dbo.users(id),  -- NULL: failed attempt before authentication
    entity        NVARCHAR(50) NOT NULL,      -- 'User' | 'Patient' | 'Consultation' | 'Prescription' | 'Appointment'
    entity_id     NVARCHAR(50) NULL,          -- GUID or integer as text; agnostic to PK type
    action        NVARCHAR(30) NOT NULL
        CHECK (action IN (N'Acceso', N'Creación', N'Modificación', N'Eliminación')),
    timestamp     DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
    ip_address    NVARCHAR(45) NULL,
    details       NVARCHAR(500) NULL
);
GO
CREATE INDEX IX_audit_log_entity ON dbo.audit_log(entity, entity_id);
CREATE INDEX IX_audit_log_user_timestamp ON dbo.audit_log(user_id, timestamp);
GO

/* =====================================================================
   2. APPOINTMENTS  (REQ-CIT-001 to 013)
   ===================================================================== */

CREATE TABLE dbo.unavailable_days (
    id      INT IDENTITY(1,1) PRIMARY KEY,
    date    DATE NOT NULL UNIQUE,
    reason  NVARCHAR(100) NULL
);
GO

-- GUID: referenced from front-desk flows (reschedule/cancel via URL).
-- patient_id is NULLABLE: an appointment can be booked for someone not yet
-- formally registered as a patient (walk-in / phone flow).
-- Note: patient_id has no REFERENCES here because dbo.patients doesn't
-- exist yet at this point in the script (appointments are documented
-- before patients in the requirements). The real constraint is added
-- further below with ALTER TABLE, once dbo.patients is created.
CREATE TABLE dbo.appointments (
    id               UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    patient_id       UNIQUEIDENTIFIER NULL,
    patient_name     NVARCHAR(100) NOT NULL,
    date             DATE NOT NULL,
    time             TIME(0) NOT NULL,
    is_first_visit   BIT NOT NULL DEFAULT 0,
    phone            NVARCHAR(15) NULL,
    affiliation      NVARCHAR(20) NULL CHECK (affiliation IN (N'Carl''s Jr', N'Pemex', N'Ninguno')),
    status           NVARCHAR(20) NOT NULL DEFAULT N'Programada'
        CHECK (status IN (N'Programada', N'Reagendada', N'Cancelada', N'Atendida')),
    created_at       DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME()
    -- Note: the "no Sundays" (REQ-CIT-011) and "20-minute time slots"
    -- (REQ-CIT-003) business rules are validated in the domain layer
    -- (HorarioCita Value Object), not here. The DB only keeps the data-
    -- integrity constraints (status/affiliation enums).
);
GO

/* =====================================================================
   3. PATIENTS  (REQ-PAC-001 to 020)
   ===================================================================== */

-- GUID as technical/API PK; record_number as a legal, independent,
-- NOT NULL UNIQUE sequential number (REQ-PAC-003).
CREATE TABLE dbo.patients (
    id                        UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    record_number             INT IDENTITY(1000,1) NOT NULL UNIQUE,
    full_name                 NVARCHAR(100) NOT NULL,
    birth_date                DATE NOT NULL,
    gender                    NVARCHAR(10) NOT NULL CHECK (gender IN (N'Masculino', N'Femenino')),
    curp                      CHAR(18) NOT NULL UNIQUE,                -- NOM-004
    address                   NVARCHAR(150) NOT NULL,
    postal_code               CHAR(5) NOT NULL,
    birth_place               NVARCHAR(100) NOT NULL,
    ethnic_group              NVARCHAR(50) NULL,                       -- NOM-004
    blood_type                NVARCHAR(3) NULL
        CHECK (blood_type IN (N'A+', N'A-', N'B+', N'B-', N'AB+', N'AB-', N'O+', N'O-')),
    guardian_name             NVARCHAR(100) NULL,
    guardian_relationship     NVARCHAR(30) NULL,
    guardian_phone            NVARCHAR(15) NULL,
    affiliation               NVARCHAR(20) NULL CHECK (affiliation IN (N'Pemex', N'Carl''s Jr', N'Ninguno')),
    private_insurance_number  NVARCHAR(30) NULL,
    other_insurance_type      NVARCHAR(50) NULL,
    insurance_number          NVARCHAR(30) NULL,
    general_notes             NVARCHAR(MAX) NULL,
    assigned_physician_id        UNIQUEIDENTIFIER NULL REFERENCES dbo.physicians(user_id),
    created_at                DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
    active                    BIT NOT NULL DEFAULT 1,              -- logical deletion: 5-year retention
    deactivated_at            DATETIME2(0) NULL
);
GO

-- Now that dbo.patients exists, add the real FK for appointments.
ALTER TABLE dbo.appointments
    ADD CONSTRAINT FK_appointments_patient FOREIGN KEY (patient_id)
    REFERENCES dbo.patients(id) ON DELETE SET NULL;
GO
CREATE INDEX IX_appointments_patient ON dbo.appointments(patient_id);
CREATE UNIQUE INDEX UX_appointments_date_time_active ON dbo.appointments(date, time)
    WHERE status <> N'Cancelada';   -- REQ-CIT-013: no double-booking (IN is not valid in filtered index predicates)
GO

CREATE INDEX IX_patients_name ON dbo.patients(full_name);          -- REQ-PAC-001
CREATE INDEX IX_patients_physician ON dbo.patients(assigned_physician_id);
GO

-- REQ-PAC-004: pathological history (1:1)
CREATE TABLE dbo.pathological_history (
    id                                INT IDENTITY(1,1) PRIMARY KEY,
    patient_id                        UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.patients(id) ON DELETE CASCADE,
    previous_illnesses                BIT NULL, previous_illnesses_type                NVARCHAR(200) NULL,
    sequelae                          BIT NULL, sequelae_type                          NVARCHAR(200) NULL,
    hospitalizations                  BIT NULL, hospitalizations_type                  NVARCHAR(200) NULL,
    surgeries                         BIT NULL, surgeries_type                         NVARCHAR(200) NULL,
    transfusions                      BIT NULL, transfusions_type                      NVARCHAR(200) NULL,
    fractures                         BIT NULL, fractures_type                         NVARCHAR(200) NULL,
    trauma_accidents                  BIT NULL, trauma_accidents_type                  NVARCHAR(200) NULL,
    childhood_exanthematous_diseases  BIT NULL, childhood_exanthematous_diseases_type  NVARCHAR(200) NULL,
    chronic_degenerative_diseases     BIT NULL, chronic_degenerative_diseases_type     NVARCHAR(200) NULL
);
GO

-- REQ-PAC-005: non-pathological history (1:1)
CREATE TABLE dbo.non_pathological_history (
    id                     INT IDENTITY(1,1) PRIMARY KEY,
    patient_id             UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.patients(id) ON DELETE CASCADE,
    housing_type           NVARCHAR(100) NULL,
    utilities              NVARCHAR(200) NULL,
    overcrowding           NVARCHAR(100) NULL,
    hygiene_habits         NVARCHAR(200) NULL,
    dietary_habits         NVARCHAR(200) NULL,
    education_level        NVARCHAR(100) NULL,
    pet_exposure           BIT NULL, pet_exposure_type      NVARCHAR(200) NULL,
    physical_activity      BIT NULL, physical_activity_type NVARCHAR(200) NULL
);
GO

-- REQ-PAC-006 / REQ-PAC-007: family history, father / mother.
-- Split into two tables because the fields aren't symmetric (mother
-- adds obstetric history), avoiding meaningless NULL columns on the father.
CREATE TABLE dbo.family_history_father (
    id                       INT IDENTITY(1,1) PRIMARY KEY,
    patient_id               UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.patients(id) ON DELETE CASCADE,
    full_name                NVARCHAR(100) NULL,
    birth_date                DATE NULL,
    occupation                NVARCHAR(50) NULL,
    smoking                   BIT NULL,
    alcohol_use                BIT NULL,
    substance_use               BIT NULL, substance_use_type         NVARCHAR(200) NULL,
    hypertension                BIT NULL,
    dysmorphic_features          BIT NULL, dysmorphic_features_type  NVARCHAR(200) NULL,
    diabetes                     BIT NULL, diabetes_type             NVARCHAR(100) NULL,   -- NOM-004: type of diabetes
    cancer                       BIT NULL, cancer_type               NVARCHAR(200) NULL,
    allergies                    BIT NULL, allergies_type            NVARCHAR(200) NULL,
    other_conditions              BIT NULL, other_conditions_type    NVARCHAR(200) NULL,
    medications                   BIT NULL, medications_type         NVARCHAR(200) NULL,
    current_health_status         NVARCHAR(100) NULL
);
GO

CREATE TABLE dbo.family_history_mother (
    id                       INT IDENTITY(1,1) PRIMARY KEY,
    patient_id               UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.patients(id) ON DELETE CASCADE,
    full_name                NVARCHAR(100) NULL,
    birth_date                DATE NULL,
    occupation                NVARCHAR(50) NULL,
    smoking                   BIT NULL,
    alcohol_use                BIT NULL,
    substance_use               BIT NULL, substance_use_type         NVARCHAR(200) NULL,
    hypertension                BIT NULL,
    dysmorphic_features          BIT NULL, dysmorphic_features_type  NVARCHAR(200) NULL,
    diabetes                     BIT NULL, diabetes_type             NVARCHAR(100) NULL,
    cancer                       BIT NULL, cancer_type               NVARCHAR(200) NULL,
    allergies                    BIT NULL, allergies_type            NVARCHAR(200) NULL,
    other_conditions              BIT NULL, other_conditions_type    NVARCHAR(200) NULL,
    medications                   BIT NULL, medications_type         NVARCHAR(200) NULL,
    current_health_status         NVARCHAR(100) NULL,
    pregnancy_count                INT NULL,
    vaginal_births_count            INT NULL,
    c_section_count                 INT NULL,
    miscarriage_count                INT NULL
);
GO

-- REQ-PAC-008
CREATE TABLE dbo.prenatal_history (
    id                          INT IDENTITY(1,1) PRIMARY KEY,
    patient_id                  UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.patients(id) ON DELETE CASCADE,
    planned_pregnancy            BIT NULL,
    fertilization_method         NVARCHAR(50) NULL CHECK (fertilization_method IN (N'Fecundación in vitro', N'Inseminación artificial', N'Ninguno')),
    prenatal_care                 BIT NULL,
    prenatal_care_start_date      DATE NULL,
    prenatal_care_provider        NVARCHAR(50) NULL,
    maternal_conditions           BIT NULL,
    condition_start_date          DATE NULL,
    condition_resolution_date     DATE NULL
);
GO

-- REQ-PAC-009
CREATE TABLE dbo.birth_history (
    id                    INT IDENTITY(1,1) PRIMARY KEY,
    patient_id            UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.patients(id) ON DELETE CASCADE,
    hospital              NVARCHAR(100) NULL,
    birth_type            NVARCHAR(20) NULL CHECK (birth_type IN (N'Natural', N'Cesárea')),
    delivery_type         NVARCHAR(20) NULL CHECK (delivery_type IN (N'Único', N'Múltiple')),
    birth_height_cm       DECIMAL(4,1) NULL,
    birth_weight_kg       DECIMAL(4,2) NULL
);
GO

-- REQ-PAC-010
CREATE TABLE dbo.postnatal_history (
    id                       INT IDENTITY(1,1) PRIMARY KEY,
    patient_id               UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.patients(id) ON DELETE CASCADE,
    required_monitoring       BIT NULL,
    required_ventilator        BIT NULL,
    required_incubator         BIT NULL,
    required_phototherapy      BIT NULL,
    phototherapy_count          INT NULL,
    other_treatments              NVARCHAR(300) NULL
);
GO

-- REQ-PAC-011
CREATE TABLE dbo.feeding_history (
    id                INT IDENTITY(1,1) PRIMARY KEY,
    patient_id        UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.patients(id) ON DELETE CASCADE,
    breastfeeding     BIT NULL, breastfeeding_months     INT NULL,
    formula           BIT NULL, formula_start_age        INT NULL,
    cereal            BIT NULL, cereal_start_age         INT NULL,
    fruits            BIT NULL, fruits_start_age         INT NULL,
    citrus            BIT NULL, citrus_start_age         INT NULL,
    vegetables        BIT NULL, vegetables_start_age     INT NULL,
    tomato            BIT NULL, tomato_start_age         INT NULL
);
GO

-- REQ-PAC-012
CREATE TABLE dbo.psychomotor_development (
    id                              INT IDENTITY(1,1) PRIMARY KEY,
    patient_id                      UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.patients(id) ON DELETE CASCADE,
    bladder_bowel_control           BIT NULL, bladder_bowel_control_age_months INT NULL,
    standing                        BIT NULL, standing_age_months              INT NULL,
    walking                         BIT NULL, walking_age_months               INT NULL,
    head_control                    BIT NULL, head_control_age_months          INT NULL,
    rolling_over                    BIT NULL, rolling_over_age_months          INT NULL,
    sitting                         BIT NULL, sitting_age_months               INT NULL,
    crawling                        BIT NULL, crawling_age_months              INT NULL
);
GO

-- REQ-PAC-013
CREATE TABLE vaccines (
    id          INT IDENTITY(1,1) PRIMARY KEY,
    name        VARCHAR(100) NOT NULL, -- E.g. 'Hepatitis B', 'Influenza', 'DPT'
    name_en     VARCHAR(100) NOT NULL,
    disease     VARCHAR(150) NOT NULL, -- E.g. 'Hepatitis B', 'Seasonal influenza', 'Diphtheria, pertussis and tetanus'
    disease_en     VARCHAR(150) NOT NULL,
    active      BIT NOT NULL DEFAULT 1
);

-- REQ-PAC-013 (Optimized)
CREATE TABLE vaccinations (
    id                    INT IDENTITY(1,1) PRIMARY KEY,
    patient_id            UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.patients(id) ON DELETE CASCADE,
    vaccine_id            INT NOT NULL REFERENCES vaccines(id),

    -- NOM requires clarity on doses/dates where available
    dose_number           INT NOT NULL DEFAULT 1, -- 1 for a single dose, or 1, 2, 3 for multi-dose schedules
    is_booster            BIT NOT NULL DEFAULT 1,  -- flags an annual or periodic booster
    administered_date     DATE NULL,               -- may be NULL if the patient doesn't recall the exact day but confirms having had it

    -- Regulatory support: how did the physician verify this information?
    verification_method   VARCHAR(50) CHECK (verification_method IN ('CARTILLA', 'INTERROGATORIO', 'EXPEDIENTE_PREVIO')),

    notes                 VARCHAR(200) NULL,              -- for adverse reactions, lot number, or brand (e.g. Pfizer, Abdala)
    created_at            DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),

    -- Prevents an exact duplicate of the same dose of the same vaccine for the same patient
    CONSTRAINT uq_patient_vaccine_dose UNIQUE (patient_id, vaccine_id, dose_number, is_booster)
);

/* CREATE TABLE dbo.vaccinations (
    id                       INT IDENTITY(1,1) PRIMARY KEY,
    patient_id               UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.patients(id) ON DELETE CASCADE,
    hepatitis_a              BIT NULL,
    hepatitis_b              BIT NULL,
    hib                      BIT NULL,
    meningococcus            BIT NULL,
    dpt                      BIT NULL,
    poliomyelitis            BIT NULL,
    rotavirus                BIT NULL,
    pneumococcus             BIT NULL,
    influenza                BIT NULL,
    mmr                      BIT NULL,
    varicella                BIT NULL,
    hpv                      BIT NULL,
    tuberculosis             BIT NULL
); */

INSERT INTO vaccines (name, name_en, disease, disease_en) VALUES
-- Infant / Basic schedule (aligned to the National Immunization Card, ages 0 to 9)
-- Esquema Infantil / Básico (Alineado a Cartilla Nacional de 0 a 9 años)
('BCG', 'BCG', 'Tuberculosis meníngea y miliar', 'Meningeal and miliary tuberculosis'),
('Hepatitis B', 'Hepatitis B', 'Infección por el virus de la Hepatitis B', 'Hepatitis B infection'),
('Hexavalente Celular / DPaT+VPI+Hib+HB', 'Hexavalent Cellular / DPaT+IPV+Hib+HB', 'Difteria, Tétanos, Tos ferina, Poliomielitis, Haemophilus influenzae tipo b y Hepatitis B', 'Diphtheria, tetanus, pertussis, poliomyelitis, Haemophilus influenzae type b and hepatitis B'),
('Rotavirus', 'Rotavirus', 'Diarrea severa por Rotavirus', 'Severe rotavirus diarrhea'),
('Neumocócica Conjugada', 'Pneumococcal Conjugate', 'Infecciones neumocócicas (Neumonía, Meningitis)', 'Pneumococcal infections (pneumonia, meningitis)'),
('Influenza Estacional', 'Seasonal Influenza', 'Influenza (Gripe estacional)', 'Seasonal influenza (flu)'),
('SRP (Triple Viral)', 'MMR (Triple Viral)', 'Sarampión, Rúbeola y Parotiditis (Paperas)', 'Measles, rubella and mumps'),
('DPT (Triple Bacteriana)', 'DPT (Triple Bacterial)', 'Difteria, Tos ferina y Tétanos', 'Diphtheria, pertussis and tetanus'),
('OPV (Sabin)', 'OPV (Sabin)', 'Poliomielitis anterior aguda', 'Acute anterior poliomyelitis'),

-- Adolescent and adult schedule (ages 10 to 59)
-- Esquema de Adolescentes y Adultos (10 a 59 años)
('SR (Doble Viral)', 'SR (Double Viral)', 'Sarampión y Rúbeola', 'Measles and rubella'),
('Td (Tétanos y Difteria)', 'Td (Tetanus and Diphtheria)', 'Tétanos y Difteria', 'Tetanus and diphtheria'),
('VPH (Virus del Papiloma Humano)', 'HPV (Human Papillomavirus)', 'Infección por VPH y Cáncer Cervicouterino', 'HPV infection and cervical cancer'),
('Tdpa', 'Tdap', 'Tétanos, Difteria y Tos ferina acelular (Especialmente en embarazadas)', 'Tetanus, diphtheria and acellular pertussis (especially for pregnant women)'),

-- Other vaccines common in the Mexican setting and for older adults
-- Otras vacunas comunes en el medio mexicano y adultos mayores
('Meningocócica', 'Meningococcal', 'Meningitis por Neisseria meningitidis', 'Meningitis caused by Neisseria meningitidis'),
('Hepatitis A', 'Hepatitis A', 'Infección por el virus de la Hepatitis A', 'Hepatitis A virus infection'),
('Varicela', 'Varicella', 'Varicela y sus complicaciones', 'Chickenpox and its complications'),
('Neumocócica Polisacárida (23 Valente)', 'Pneumococcal Polysaccharide (23-valent)', 'Infecciones neumocócicas en adultos mayores y grupos de riesgo', 'Pneumococcal infections in older adults and at-risk groups'),
('COVID-19', 'COVID-19', 'Infección por el virus SARS-CoV-2 (Coronavirus)', 'SARS-CoV-2 virus infection (Coronavirus)');

GO

-- REQ-PAC-014
CREATE TABLE dbo.allergies (
    id                INT IDENTITY(1,1) PRIMARY KEY,
    patient_id        UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.patients(id) ON DELETE CASCADE,
    medications       BIT NULL, medication_agents NVARCHAR(200) NULL,
    food              BIT NULL, food_agents        NVARCHAR(200) NULL,
    pollen            BIT NULL, pollen_agents      NVARCHAR(200) NULL,
    fabric            BIT NULL, fabric_agents      NVARCHAR(200) NULL
);
GO

/* =====================================================================
   4. CONSULTATIONS  (REQ-CON-001 to 008)
   ===================================================================== */

CREATE TABLE dbo.consultations (
    id                            UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    patient_id                    UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.patients(id),   -- no CASCADE: medical-legal record
    physician_id                     UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.physicians(user_id), -- REQ-CON-003/004
    consultation_date             DATE NOT NULL,
    consultation_time             TIME(0) NOT NULL DEFAULT CONVERT(TIME(0), SYSUTCDATETIME()),
    reason                        NVARCHAR(100) NOT NULL,
    heart_rate                    INT NOT NULL,
    respiratory_rate              INT NOT NULL,
    systolic_pressure             INT NOT NULL,
    diastolic_pressure            INT NOT NULL,
    temperature                   DECIMAL(4,1) NOT NULL,
    weight                        DECIMAL(5,2) NOT NULL,
    height                        DECIMAL(5,2) NOT NULL,
    general_appearance            NVARCHAR(300) NULL,
    skin_and_appendages           NVARCHAR(300) NULL,
    head                          NVARCHAR(300) NULL,
    neck                          NVARCHAR(300) NULL,
    chest                         NVARCHAR(300) NULL,
    abdomen                       NVARCHAR(300) NULL,
    extremities                   NVARCHAR(300) NULL,
    image                         VARBINARY(MAX) NULL,
    previous_test_results         NVARCHAR(MAX) NULL,
    diagnosis                     NVARCHAR(MAX) NOT NULL,
    icd10_diagnosis                NVARCHAR(10) NULL,             -- NOM-004
    present_illness                 NVARCHAR(MAX) NULL,           -- NOM-004
    prognosis                       NVARCHAR(MAX) NOT NULL,
    treatment_instructions           NVARCHAR(MAX) NULL,
    created_at                       DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
    active                           BIT NOT NULL DEFAULT 1
);
GO
CREATE INDEX IX_consultations_patient ON dbo.consultations(patient_id, consultation_date DESC);   -- REQ-CON-007
CREATE INDEX IX_consultations_physician ON dbo.consultations(physician_id);
GO

-- REQ-CON-001: previous treatments, 0..N list
CREATE TABLE dbo.consultation_previous_treatments (
    id                     INT IDENTITY(1,1) PRIMARY KEY,
    consultation_id        UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.consultations(id) ON DELETE CASCADE,
    brand_name             NVARCHAR(100) NULL,
    active_ingredient      NVARCHAR(100) NULL,
    dose                   NVARCHAR(50) NULL,
    route                  NVARCHAR(30) NULL,
    frequency              NVARCHAR(50) NULL,
    administration_date    DATE NULL,
    administration_time    TIME(0) NULL
);
GO

-- REQ-CON-001: review of systems (1:1)
CREATE TABLE dbo.consultation_review_of_systems (
    id                              INT IDENTITY(1,1) PRIMARY KEY,
    consultation_id                 UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.consultations(id) ON DELETE CASCADE,
    respiratory_cardiovascular      NVARCHAR(300) NULL,
    digestive                       NVARCHAR(300) NULL,
    endocrine                       NVARCHAR(300) NULL,
    musculoskeletal                 NVARCHAR(300) NULL,
    genitourinary                   NVARCHAR(300) NULL,
    hematopoietic_lymphatic         NVARCHAR(300) NULL,
    skin_and_appendages             NVARCHAR(300) NULL,
    neurological_psychiatric        NVARCHAR(300) NULL
);
GO

/* =====================================================================
   5. PRESCRIPTIONS  (REQ-REC-001 to 008)
   ===================================================================== */

CREATE TABLE dbo.prescriptions (
    id                     UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    prescription_number    INT IDENTITY(1000,1) NOT NULL UNIQUE,     -- REQ-REC-002: printed prescription number
    patient_id             UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.patients(id),
    consultation_id        UNIQUEIDENTIFIER NULL REFERENCES dbo.consultations(id),
    physician_id              UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.physicians(user_id),
    issue_date              DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
    weight                   DECIMAL(5,2) NULL,
    height                   DECIMAL(5,2) NULL,
    bmi                      AS (CASE WHEN height > 0 THEN weight / ((height / 100.0) * (height / 100.0)) END) PERSISTED,  -- REQ-REC-002
    blood_pressure           VARCHAR(8) NULL,
    temperature               DECIMAL(4,1) NULL,
    diagnosis                  NVARCHAR(MAX) NULL,
    status                     NVARCHAR(20) NOT NULL DEFAULT N'Emitida'
        CHECK (status IN (N'Emitida', N'Cancelada')),             -- REQ-REC-005: cancel, don't delete
    created_at                 DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
CREATE INDEX IX_prescriptions_patient ON dbo.prescriptions(patient_id, issue_date DESC);   -- REQ-REC-004
GO

-- REQ-REC-001: prescribed medications, 1..N list
CREATE TABLE dbo.prescription_medications (
    id                    INT IDENTITY(1,1) PRIMARY KEY,
    prescription_id       UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.prescriptions(id) ON DELETE CASCADE,
    generic_name          NVARCHAR(100) NOT NULL,
    form                  NVARCHAR(20) NOT NULL CHECK (form IN (N'Tabletas', N'Solución')),
    dose                  NVARCHAR(50) NOT NULL,
    frequency_hours       INT NOT NULL,
    administration_route  NVARCHAR(20) NOT NULL CHECK (administration_route IN (N'Oral', N'Intravenosa')),
    instructions           NVARCHAR(200) NULL,
    duration_days           INT NOT NULL
);
GO

/* =====================================================================
   6. STATISTICS  (REQ-EST-001 to 004)
   ===================================================================== */

-- WHO reference table (LMS), static, no external exposure: no GUID.
CREATE TABLE dbo.who_growth_standards (
    id          INT IDENTITY(1,1) PRIMARY KEY,
    indicator   NVARCHAR(20) NOT NULL,     -- 'WeightForAge','HeightForAge', etc.
    gender      NVARCHAR(10) NOT NULL,
    age_months  INT NULL,
    measurement NVARCHAR(10) NULL,
    l           FLOAT NULL,
    m           FLOAT NULL,
    s           FLOAT NULL
);
GO
CREATE INDEX IX_who_growth_standards_lookup ON dbo.who_growth_standards(indicator, gender, age_months);
GO

PRINT 'Pediatrics V6.1 schema (SQL Server) created successfully.';
GO
